(deftheme whiteboard
  "Created 2018-12-07.")

(custom-theme-set-faces
 'whiteboard
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "DarkGreen"))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "Red1"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight normal :foreground "DeepSkyBlue4"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "DarkGreen"))))
 '(cursor ((((class color) (min-colors 89)) (:background "Green4"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:background nil :underline "red"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:background nil :underline "magenta3"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "DarkOrange3"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen4"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "peru"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod3"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DodgerBlue2"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold3"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood4"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue4"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "SeaGreen4"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(fringe ((((class color) (min-colors 89)) (:background "gainsboro"))))
 '(highlight ((((class color) (min-colors 89)) (:background "SkyBlue1"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "coral4" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "LightPink1"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "DodgerBlue4"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(region ((((class color) (min-colors 89)) (:background "SkyBlue1"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "Yellow4"))))
 '(default ((((class color) (min-colors 89)) (:background "whitesmoke" :foreground "black")))))

(provide-theme 'whiteboard)
